name: Create Release

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Tarball
        run: |
          ls -la
          tar -cJf lingmo-alpine-fontpkg.tar.xz .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: lingmo-alpine-fontpkg.tar.xz
            name: Release ${{ github.ref_name }}

      - name: Cleanup
        run: rm lingmo-alpine-fontpkg.tar.xz
