name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: tar
        run: |
          ls -la
          tar -cJf lingmo-alpine-fontpack.tar.xz ./*

      - name: Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: lingmo-alpine-fontpack.tar.xz
