name: Create Release

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Tarball
        run: |
          ls -la
          mkdir -p lingmo-fontpkg
          cp -R $(ls | grep -xv lingmo-fontpkg) lingmo-fontpkg/
          tar -cJf lingmo-fontpkg.tar.xz lingmo-fontpkg

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: lingmo-fontpkg.tar.xz
            name: Release ${{ github.ref }}

      - name: Cleanup
        run: rm lingmo-fontpkg.tar.xz
